Add multipart request for video large binary object
ErnestasSku/AEZAKMI pull request #8
Opened 2023-05-09 19:49 UTC by viliusjun

2023-05-10 13:27 UTC, audrius-savickas reviewed
How is performance affected when a large file is being uploaded? Do other endpoints and DB CRUD still work?

2023-05-10 13:41 UTC, audrius-savickas requested changes

2023-05-10 13:41 UTC, audrius-savickas commented on src/main/java/com/vu/aezakmi/multipartRequest/VideoUploadRequest.java
> +    private VideoDto videoDto;
hmm, client would have to pass `videoDto.title`, `videoDto.description` in its POST body. Would be nicer to have just straight up title, description, etc. in the body.

2023-05-10 13:41 UTC, audrius-savickas commented on src/main/java/com/vu/aezakmi/multipartRequest/VideoUploadRequest.java
> +    private VideoDto videoDto;
also, video DTO still has fileURL as one of its fields

2023-05-12 17:17 UTC, scasm approved these changes

2023-05-12 17:17 UTC, merged